/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiuyue_tanyscan_activity_LibImgFun */

#ifndef _Included_com_appxy_tools_LibImgFun
#define _Included_com_appxy_tools_LibImgFun
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL Java_com_appxy_tools_LibImgFun_ImgFunInt
  (JNIEnv *, jclass, jstring path);



JNIEXPORT void JNICALL Java_com_appxy_tools_LibImgFun_Transfer(
		JNIEnv* env, jobject obj, jstring path, jintArray data, jstring newpath, jint degree);


#ifdef __cplusplus
}
#endif
#endif
